#!/usr/bin/env bash

set -e

LC_ALL=C

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR="$SCRIPT_DIR/../.."

TMP_DIR=`mktemp -d`

###################

mkdir -p "$TMP_DIR/data"

cp "$ROOT_DIR/data/archive-part"{1.tar,2.zip} "$TMP_DIR/data"

echo "Test case #1"

cd "$TMP_DIR"

bash "$ROOT_DIR/solution/task1.sh"

diff -U 1000 \
  <(cat "$SCRIPT_DIR/out.expected" | sort) \
  <(tar -tf "$TMP_DIR/data/archive-combined.tar.gz" \
    | sed '/^\.\/$/d' | sed 's/^\.\///' | sort)
#     ^ Try to tolerate starting './' in the archived paths
