#!/usr/bin/env bash

source ../common.sh

###################

cp -r "$ROOT_DIR/data" "$TMP_DIR/data"

echo "Test case #1"

cd "$TMP_DIR"

bash "$ROOT_DIR/solution/task1.sh"

diff -U 1000 \
  <(cat "$SCRIPT_DIR/task1/out.expected") \
  <(tar -tf "$TMP_DIR/data/archive-combined.tar.gz" \
    | sed '/^\.\/$/d' | sed 's/^\.\///')
#     ^ Try to tolerate starting './' in the archived paths
